extends Node2D
# Rusted Pulse Unleashed — ACTION
# Generated by DeathRoll Studio v3.0
# Mechanic: Every death upgrades one random stat permanently

const GAME_TITLE = "Rusted Pulse Unleashed"
const GENRE = "action"
const LICENSE_KEY = "DRS-VDFL-YETK-Z0KE-BHY1"

var score: int = 0
var player_lives: int = 3
var game_active: bool = false

func _ready() -> void:
    print("=== %s ===" % GAME_TITLE)
    print("Genre: %s" % GENRE)
    print("Licensed to: %s" % LICENSE_KEY)
    _start_game()

func _start_game() -> void:
    game_active = true
    score = 0
    player_lives = 3
    print("Game started!")

func _process(delta: float) -> void:
    if not game_active:
        return
    _update_game(delta)

func _update_game(delta: float) -> void:
    # TODO: Implement action game logic
    # Mechanic: Every death upgrades one random stat permanently
    pass

func add_score(points: int) -> void:
    score += points
    print("Score: %d" % score)

func lose_life() -> void:
    player_lives -= 1
    if player_lives <= 0:
        _game_over()

func _game_over() -> void:
    game_active = false
    print("Game Over! Final Score: %d" % score)
